### ISSUE TITLE
[ List image metadata ]

### ISSUE THREAD

**Issue by LukyVj** [cloudinary/cloudinary-js-base#198]
## Feature request for Cloudinary JS SDK
Hello! I'm using your SDKs on a react project, and I would need to be able to display the images custom metadata. 

Unfortunately, I haven't found any resources about it. Only for nodeJS which isn't what I'm looking for. 

Is there any way to access image metadata with CloudinaryJS? Like by doing 
```
cloudinary.url('url/path').metadata // => [{key: value}, {key: value}, ...]
```

**Comment by aditimadan-Cloudinary** [comment]
You can get the metadata on the client-side is by using tags. `http://res.cloudinary.com/<your_cloud_name>/<resource_type>/list/<tag>.json`. This will return a json with the metadata/context information. 
More information here:https://support.cloudinary.com/hc/en-us/articles/203189031-How-to-retrieve-a-list-of-all-resources-sharing-the-same-tag-

**Comment by LukyVj** [comment]
Hey @aditimadan-Cloudinary Thanks a lot for answering. 

I have a hard time understanding how to use this. The documentation isn't really straightforward on that. 

If I want to list ALL metadata of a specific image. How can I do? 
I've tried this: `cl.url('logo', { format: 'json', type: 'list' })` which give me a 404 url. 

What would be the correct way to generate an URL that would give me metadata informations for a specific image? 


Thank you.

**Comment by aditimadan-Cloudinary** [comment]
We don't have it integrated into React yet, but you can simply use the Javascript fetch and call the tag.json URL.

**Comment by patrick-tolosa** [comment]
I see you've opened a duplicate issue - https://github.com/cloudinary/cloudinary_js/issues/263#issuecomment-715476122 and you've got some answers there as well.

Please feel free to continue the discussion there.
Your question also best fits that repository, as this one contains code for the next generation of the cloudinary JS SDK, and your question is around the existing one.

**Comment by LukyVj** [comment]
Thanks a lot @patrick-tolosa will do! Keep it up :)
